baseURL = "https://pyxback.pages.dev/"
absURL= "https://pyxback.pages.dev"
languageCode = "en-en"
title = "Pyxill 2"

contentdir = "content"
publishdir = "public"
builddrafts = false
theme = "pyxill2"
ignoreFiles = [ "\\.db$","\\.css$"]
pygmentsUseClassic=false
pygmentsStyle="dracula"
pygmentsCodefences=true
pygmentsOptions="linenos=false"
Paginate= 10
relativeURLs = true
canonifyURLs= false
enableEmoji = true


[indexes]
  category = "categories"
  tag = "tags"

[params]
  avatar="local" #you can choose between graveyard, libravatar or local
  admin_hash="d959b6db5935acae2c0aeac2956f2c13"
#  admin_hash="hashofyouremail" #in case of local
  math_library="katex" #you can choose between katex or mathjax depending on your needs
  hostName = "https://pyxback.pages.dev"
  toc= true
  absURL= "https://pyxback.pages.dev"
  mainSections = ["post"]
  bg_color= "#3b4252"
  theme_color= "#4c566a"
  twitter_username = "gohugoio"
  paginate = 10
  description = "A minimal theme for Hugo"
  author = "Iacopo Moles"
  banner= "banner.png"
  staticman_api = "https://staticman-tutorial-hugo.herokuapp.com/v2/entry/IcpMoles/pyxback/main/comments" #Add staticman API URL to enable staticman comments
 #  RssUrl =  "https://example.com/rss"
  google_analytics_id = "73mlN4x3UZrTPxQ07EkDwLhKXo2GPTaP8JWKfg5vhWg"
  flattr_id = "e0v7jk"
  payment_pointer = "$ilp.uphold.com/kk3ZPeDi34nP"
  google_analytics_js = false
  js_privacy = true #uses locally hosted libraries instead of using their CDN
  footer_links = true #enables a footer navigation bar
  custom_navbar = true #makes the main navbar editable
  custom_footbar = true #maked the footbare editable 
  [params.alert]
    warning="⚠️"
    error="❗"
    success="✔"
    info="ℹ️"


[author]
  name = "Author"
	
[outputs]
  home = ["HTML", "AMP", "RSS"]
  page = ["HTML", "AMP", "RSS"]

  
[privacy]
  [privacy.instagram]
    disable = false
    simple = true
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = true
  [privacy.vimeo]
    disable = false
    simple = true
  [privacy.youtube]
    disable = false
    privacyEnhanced = true 
    

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = -90

  [[menu.main]]
    name = "Archive"
    url = "/archives/"
    weight = -100

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = -110

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = -120
 

  [[menu.footer]]
    name = "Privacy Policy"
    url = "/privacy-policy/"
    weight = -90
    pre=""

  [[menu.footer]]
    name = "Credits"
    url = "/credits/"
    weight = -100
    pre=" | "

  [[menu.footer]]
    name = "Admin"
    url = "/netlify/"
    weight = -110
    pre=" | "

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
